### ISSUE TITLE
[nodemon] app crashed

### ISSUE THREAD

**Issue by Alexchertkov** [hobo05/nginx-graph#1]
Hi!

Trying to run it locally.

npm install - ok (after I updated many packages such as gcc 4.9+ and more)
Then tried npm run local-dev and got this:
`> nginx-graph@1.0.0 local-dev /srv/nginx-graph
> nodemon server

[nodemon] 1.19.4
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 22802 to restart
[nodemon] ignoring: src/**/* dist/**/*
[nodemon] watching dir(s): *.* .nginxGraphrc
[nodemon] watching extensions: js,json,html,css
[nodemon] starting `node server server.js`
[nodemon] forking
[nodemon] child pid: 22813
process.env.NODE_ENV=development
undefined:40
        }]
        ^

SyntaxError: Unexpected token } in JSON at position 1330
    at Object.parse (native)
    at exports.parse (/srv/nginx-graph/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/srv/nginx-graph/node_modules/rc/index.js:30:20)
    at module.exports (/srv/nginx-graph/node_modules/rc/index.js:44:3)
    at Object.<anonymous> (/srv/nginx-graph/lib/config.js:21:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] watching 60 files
`

**Comment by Alexchertkov** [comment]
Installs correctly

> nodegit@0.16.0 install /srv/nginx-graph/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
[nodegit] Success: "/srv/nginx-graph/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> core-js@2.6.12 postinstall /srv/nginx-graph/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> nodegit@0.16.0 postinstall /srv/nginx-graph/node_modules/nodegit
> node lifecycleScripts/postinstall


> nodemon@1.19.4 postinstall /srv/nginx-graph/node_modules/nodemon
> node bin/postinstall || exit 0

**Comment by Alexchertkov** [comment]
Installs correctly

> nodegit@0.16.0 install /srv/nginx-graph/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
[nodegit] Success: "/srv/nginx-graph/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> core-js@2.6.12 postinstall /srv/nginx-graph/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> nodegit@0.16.0 postinstall /srv/nginx-graph/node_modules/nodegit
> node lifecycleScripts/postinstall


> nodemon@1.19.4 postinstall /srv/nginx-graph/node_modules/nodemon
> node bin/postinstall || exit 0

**Comment by Alexchertkov** [comment]
Problem is in the comma after conf" in .nginxGraphrc:
{
		"key": "Second Domain",
		"path": "prod/conf.d/second/second.com.conf"**_,_**
	}]
